### PR TITLE
update to grunt-jasmine-node2 for integration tests

### PR DESCRIPTION
**Pull request by soycode**
Changing to the newer grunt-jasmine-node2 didn't go quite as smoothly for this repo. The tests do pass with these changes along with this branch of freedom: https://github.com/freedomjs/freedom/compare/soycode-nodeintegration

Much of the diff is just cleanup, main logic changes:
-storage.get in freedom-for-node more explicitly returns null instead of undefined (was failing "resolves 'null' when getting unset keys" without this)
-afterGet in storage.integration.src.js (freedom repo) allows null or undefined (still necessary for several of the tests even with storage.get returning explicit null)
-One of the tcpsocket tests is commented out ("works as a client") - it fails in some creative fashion that actually causes all tests after it to fail, so presumably timeout related

I'm creating a pull request for this as I do think these changes make sense to merge, but don't like the changes in the freedom repo. Obviously just disabling the TCP test is a cop out, and further I would like to figure the undefined-versus-null thing a bit more. I may still want to merge that branch after a bit more work on it, as the cleanup stuff (using ===, jshint, etc.) is worth it.

In any case I don't feel too urgent about this but am documenting it for my own purposes if nothing else. Thoughts of course are welcome.

### CODE REVIEW

**Comment by ryscheng** [comment]
:+1:

**Comment by soycode** [comment]
Our celebration may have been premature - travis considers the test green (and npm test exits with 0), but the actual output has a "fatal error": https://travis-ci.org/freedomjs/freedom-for-node/builds/47834102#L196

It's not clear to me that the usual expects are happening, or if the test is just somehow short-circuited.

**Comment by soycode** [comment]
Verbose output: https://travis-ci.org/freedomjs/freedom-for-node/builds/47837594

Looks like most tests do pass, some social test fails but I'm not sure that's related to any of this (maybe flaky), and the "fatal error" looks to happen during the TCP tests (the first one passes, the latter ones never happen). Overall it's not *terrible* but I would like to figure what's happening w/TCP.

**Comment by soycode** [comment]
After much trial and error, I discovered that for some reason, having any test (even a simple it("does stuff", function (done) { done(); });) ahead of the "Gets info" test (for tcpsocket.integration.src.js) causes some strange condition where node just fails. I still don't know the *real* reason, but after digging pretty deep I found that this pull request plus this other one (https://github.com/freedomjs/freedom/pull/218) allows all tests to pass.

I don't like how the order of otherwise identical tests matters for their testing, and it may indicate an actual issue with the underlying library, but for now I think getting these changes in would at least be a step in the right direction. Let me know thoughts, thanks!

**Comment by soycode** [comment]
Now passes with the better accompanying pull request of: https://github.com/freedomjs/freedom/pull/221

Went ahead and pushed another commit to guarantee that the "connecting" status is set, I don't believe it was causing the issue in this case but seems a good change to me nonetheless.

**Comment by willscott** [comment]
:+1:

**Pull request merged**
